### ISSUE TITLE
Webex

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-cisco-collaboration-endpoints#3]
Hi,

We might be developing towards the same kind of devices in two separate modules.

Would you please look at companion-cisco-webex, and see if there is something this module will be able to do that the mentioned one will not?

It will have event-based feedback support (no polling) but is currently only able to dial numbers and check the status of ingoing/outgoing calls, but more features will be added soon. It is being created on request from Cisco in Norway.

Maybe you would like to help us develop that module instead? Unless I have misunderstood, and this module is very different.

**Comment by thomascantrellsea** [comment]
Haakon - thanks for letting me know, I reached out on Slack. We can chat for a bit.

**Comment by thomascantrellsea** [comment]
At the end of the day Haakon's work morphed into some development and ended up as: https://github.com/bitfocus/companion-module-cisco-webex-websocket. I'm looking at Haakon and Jeffrey's work and likely to sunset this module in a bit.
