### ISSUE TITLE
C40 and P60 for testing

### ISSUE THREAD

**Issue by nottooloud** [bitfocus/companion-module-cisco-collaboration-endpoints#4]
Sorry for posting as an issue, discussions aren't enabled.
I have a C40 and several P60 cameras. Would love to test any camera controls.

**Comment by yurividal** [comment]
I have some DX80 and SX80. Would also love to help testing

**Comment by thomascantrellsea** [comment]
Have you tried the new module (https://github.com/bitfocus/companion-module-cisco-webex-websocket) available in mainline with your C40 and P60. I know it's not just the device, it's also the firmware version.

**Comment by nottooloud** [comment]
Yes. I have several issues open over there. We can close this issue, and really should just point to that project. Especially now that they've implemented xCommand and xConfig. It's quite usable.
